(function(){
'use strict';
var CHINA_TZ='Asia/Shanghai', RUN_KEY='china-trip-2026-daily-state-v3', run={};try{run=JSON.parse(localStorage.getItem(RUN_KEY)||'{}')}catch(e){}
function save(){localStorage.setItem(RUN_KEY,JSON.stringify(run))}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function parts(){var p=new Intl.DateTimeFormat('en-CA',{timeZone:CHINA_TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()),o={};p.forEach(function(x){if(x.type!=='literal')o[x.type]=x.value});return{date:o.year+'-'+o.month+'-'+o.day,mins:+o.hour*60 + +o.minute,clock:o.hour+':'+o.minute}}
function min(s){if(!s||!/^[0-2]?\d:[0-5]\d$/.test(s))return null;var a=s.split(':').map(Number);return a[0]*60+a[1]}
function hm(m){m=(m+1440)%1440;return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
function items(){return (window.ITINERARY||[]).filter(function(i){return i.active!==false}).slice().sort(function(a,b){return a.date.localeCompare(b.date)||(min(a.start)||9999)-(min(b.start)||9999)||String(a.time).localeCompare(String(b.time))})}
function byDate(d){return items().filter(function(i){return i.date===d})}
function travelBuffer(i){if(i.leaveBuffer!=null)return i.leaveBuffer;if(i.type==='flight')return 150;if(i.type==='train')return 90;if(i.type==='tour')return 35;if(i.type==='attraction'||i.type==='activity')return 30;if(i.type==='transfer')return 10;return 20}
function leave(i){var m=min(i.start);return m==null?'—':hm(m-travelBuffer(i))}
function svg(name){var p={
clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',walk:'<circle cx="12" cy="5" r="2"/><path d="M10 9l2 3 3 1M12 12l-2 6M13 12l4 5"/>',car:'<path d="M5 15l1-5h12l1 5"/><path d="M4 15h16v4H4z"/><circle cx="7" cy="19" r="1"/><circle cx="17" cy="19" r="1"/>',train:'<rect x="5" y="3" width="14" height="15" rx="3"/><path d="M8 7h8M8 12h3M13 12h3M8 21l2-3M16 21l-2-3"/>',flight:'<path d="M3 13l18-8-7 14-2-6-6-2z"/>',ticket:'<path d="M4 7h16v4a2 2 0 000 4v4H4v-4a2 2 0 000-4z"/><path d="M12 7v12"/>',note:'<path d="M6 3h9l3 3v15H6z"/><path d="M15 3v4h4M9 11h6M9 15h6"/>',zh:'<path d="M5 5h14M12 3v17M7 9h10M8 14h8"/>',pin:'<path d="M12 21s6-5.2 6-11a6 6 0 10-12 0c0 5.8 6 11 6 11z"/><circle cx="12" cy="10" r="2"/>',hotel:'<path d="M5 21V6h14v15M8 10h2M14 10h2M8 14h2M14 14h2M10 21v-4h4v4"/>',food:'<path d="M7 3v8M4 3v4c0 2 1 4 3 4s3-2 3-4V3M16 3v18M16 3c3 2 3 7 0 9"/>',bag:'<rect x="5" y="7" width="14" height="13" rx="2"/><path d="M9 7V5h6v2"/>',map:'<path d="M4 6l5-2 6 2 5-2v14l-5 2-6-2-5 2zM9 4v14M15 6v14"/>',check:'<path d="M5 12l4 4L19 6"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',bell:'<path d="M6 16h12l-2-3V9a4 4 0 00-8 0v4zM10 19h4"/>',mountain:'<path d="M3 19l6-10 4 6 2-3 6 7z"/>',city:'<path d="M4 20V9h5v11M10 20V4h6v16M17 20v-8h3v8"/>',temple:'<path d="M4 10h16M6 10v10M18 10v10M8 14h8M9 20v-6M15 20v-6M3 10l9-6 9 6"/>',boat:'<path d="M4 14h16l-3 5H7zM12 5v9M12 5l5 5h-5"/>',shop:'<path d="M5 9h14l-1-4H6zM6 9v11h12V9M9 13h6"/>'};return '<svg viewBox="0 0 24 24" aria-hidden="true">'+(p[name]||p.pin)+'</svg>'}
function transportIcon(i){if(i.type==='flight')return 'flight';if(i.type==='train')return 'train';if(i.type==='transfer')return 'car';if(i.transport&&/walk/i.test(i.transport))return 'walk';return 'walk'}
function itemIcon(i){return ({flight:'flight',train:'train',transfer:'car',hotel:'hotel',restaurant:'food',shopping:'shop',arrival:'pin',attraction:'temple',tour:'map',activity:'boat',area:'walk'})[i.type]||'pin'}
function theme(a){var c=a.city||'';if(a.day===14||/Suzhou/i.test(a.name||''))return 'suzhou';if(c==='Beijing')return 'beijing';if(c==='Xi’an')return 'xian';if(c==='Chengdu')return 'chengdu';if(c==='Zhangjiajie')return 'zhangjiajie';if(c==='Yangshuo')return 'yangshuo';return 'shanghai'}
function landmark(t){var k=t==='zhangjiajie'?'mountain':t==='yangshuo'?'mountain':t==='shanghai'?'city':t==='suzhou'?'boat':'temple';return '<div class="day-landmark event-icon">'+svg(k)+'</div>'}
function statusTags(i){var r='';if(i.locked)r+='<span class="tag fixed">FIXED</span>';if(i.optional)r+='<span class="tag optional">OPTIONAL</span>';if(i.pending)r+='<span class="tag pending">PENDING</span>';return r}
function bundle(i){var out=[];out.push('<button type="button"><span class="action-ico">'+svg('clock')+'</span>'+esc(i.time)+'</button>');if(min(i.start)!=null&&i.type!=='arrival'&&i.type!=='hotel')out.push('<button type="button"><span class="action-ico">'+svg(transportIcon(i))+'</span>Leave '+leave(i)+'</button>');if(i.bookable)out.push('<button type="button" data-open-booking="'+esc(i.id)+'"><span class="action-ico">'+svg('ticket')+'</span>Ticket</button>');if(i.nameZh)out.push('<button type="button" data-driver="'+esc(i.id)+'"><span class="action-ico">'+svg('zh')+'</span>中文</button>');if(i.notes)out.push('<button type="button" data-note="'+esc(i.id)+'"><span class="action-ico">'+svg('note')+'</span>Note</button>');return '<div class="bundle">'+out.join('')+'</div>'}
function currentIndex(a,mins){var usable=a.filter(function(i){return min(i.start)!=null&&!((run[i.id]||{}).skipped)}),idx=-1;usable.forEach(function(i,k){if(min(i.start)<=mins)idx=k});return idx<0?usable[0]||null:usable[idx]||null}
function eventRow(i,isCurrent,live){var s=run[i.id]||{},cls='event-row'+(isCurrent?' current-event':'');return '<div class="'+cls+'" data-event-id="'+esc(i.id)+'"><div class="event-time">'+esc(i.time)+'</div><div class="event-icon">'+svg(itemIcon(i))+'</div><div><div class="event-name">'+esc(i.name)+'</div><div class="event-zh">'+esc(i.nameZh||'')+'</div><div class="day-status">'+statusTags(i)+'</div>'+(i.notes?'<div class="event-note">'+esc(i.notes)+'</div>':'')+bundle(i)+(live&&isCurrent?'<div class="live-controls"><button class="done" data-act="done" data-id="'+i.id+'">'+(s.done?'Undo':'Done')+'</button><button class="skip" data-act="skip" data-id="'+i.id+'">'+(s.skipped?'Restore':'Skip')+'</button><button class="late" data-act="late">Running late</button></div>':'')+'</div></div>'}
function dayCard(date,cp){var a=byDate(date);if(!a.length)return '';var t=theme(a[0]),live=date===cp.date,cur=live?currentIndex(a,cp.mins):null;var rows=a.map(function(i){return eventRow(i,cur&&cur.id===i.id,live)}).join('');var next='';if(live&&cur){var ix=a.findIndex(function(x){return x.id===cur.id}),n=a.slice(ix+1).find(function(x){return min(x.start)!=null});if(n)next='<div class="next-brief"><div class="label">NEXT</div><strong>'+esc(n.name)+'</strong><small>'+esc(n.time)+' · leave '+leave(n)+'</small></div>'}return '<section class="day-card theme-'+t+(live?' current-day':'')+'" id="day-'+date+'" data-date="'+date+'"><div class="day-hero"><div class="day-hero-copy"><div class="day-kicker">DAY '+a[0].day+' · '+esc(date)+'</div><h2>'+esc(a[0].city.replace(' + Suzhou',''))+'</h2><div class="zh">'+esc(a[0].cityZh||'')+'</div></div>'+landmark(t)+'</div>'+next+'<div class="timeline-list">'+rows+'</div></section>'}
function tomorrowDate(d){var x=new Date(d+'T00:00:00Z');x.setUTCDate(x.getUTCDate()+1);return x.toISOString().slice(0,10)}
var idleTimer=null;function armReturn(){clearTimeout(idleTimer);var cp=parts();if(cp.date<'2026-09-05'||cp.date>'2026-09-21')return;idleTimer=setTimeout(function(){scrollCurrent(true)},12000)}
function scrollCurrent(smooth){var cp=parts(),day=document.getElementById('day-'+cp.date);if(!day)return;var cur=day.querySelector('.current-event');(cur||day).scrollIntoView({behavior:smooth?'smooth':'auto',block:'center'})}
function render(){var host=document.getElementById('dailyAssistant');if(!host)return;var cp=parts(),dates=[...new Set(items().map(function(i){return i.date}))];host.className='daily-assistant-v3'+(run.travelMode?' travel-mode':'');var top='<div class="today-topline"><div class="today-clock">CHINA TIME · '+cp.clock+'</div><div><button class="today-travel-toggle" id="travelModeV3">'+(run.travelMode?'EXIT TRAVEL':'TRAVEL MODE')+'</button> <button class="today-return" id="returnNow">'+(cp.date>='2026-09-05'&&cp.date<='2026-09-21'?'BACK TO NOW':'DAY 1')+'</button></div></div>';host.innerHTML=top+dates.map(function(d){return dayCard(d,cp)}).join('');wire();setTimeout(function(){if(cp.date>='2026-09-05'&&cp.date<='2026-09-21')scrollCurrent(false)},80);armReturn()}
function noteSheet(i){var old=document.getElementById('driverSheetV3');if(old)old.remove();var d=document.createElement('div');d.id='driverSheetV3';d.className='driver-sheet-v3';d.innerHTML='<button class="close">×</button><div class="label">NOTE</div><div class="driver-en">'+esc(i.notes||'No note')+'</div>';document.body.appendChild(d);d.querySelector('.close').onclick=function(){d.remove()}}
function driver(i){var old=document.getElementById('driverSheetV3');if(old)old.remove();var d=document.createElement('div');d.id='driverSheetV3';d.className='driver-sheet-v3';d.innerHTML='<button class="close">×</button><div class="label">PLEASE TAKE ME TO</div><div class="driver-zh">'+esc(i.nameZh||i.name)+'</div><div class="driver-en">'+esc(i.name)+'</div>';document.body.appendChild(d);d.querySelector('.close').onclick=function(){d.remove()}}
function wire(){var tm=document.getElementById('travelModeV3');if(tm)tm.onclick=function(){run.travelMode=!run.travelMode;save();render()};var rn=document.getElementById('returnNow');if(rn)rn.onclick=function(){var cp=parts();if(cp.date>='2026-09-05'&&cp.date<='2026-09-21')scrollCurrent(true);else document.getElementById('day-2026-09-05').scrollIntoView({behavior:'smooth'})};document.querySelectorAll('[data-driver]').forEach(function(b){b.onclick=function(){var i=items().find(function(x){return x.id===b.dataset.driver});if(i)driver(i)}});document.querySelectorAll('[data-note]').forEach(function(b){b.onclick=function(){var i=items().find(function(x){return x.id===b.dataset.note});if(i)noteSheet(i)}});document.querySelectorAll('[data-open-booking]').forEach(function(b){b.onclick=function(){if(typeof openDlg==='function')openDlg(b.dataset.openBooking)}});document.querySelectorAll('[data-act]').forEach(function(b){b.onclick=function(){var id=b.dataset.id,act=b.dataset.act;if(act==='late'){run.lateAt=Date.now()}else{run[id]=run[id]||{};if(act==='done'){run[id].done=!run[id].done;run[id].skipped=false}if(act==='skip'){run[id].skipped=!run[id].skipped;run[id].done=false}}save();render()}})}
function modernNav(){var nav=document.querySelector('.bottom-nav');if(!nav)return;var defs=[['dashboard','pin','Today'],['timeline','map','Trip'],['tickets','ticket','Tickets'],['checklist','check','Checklist'],['more','more','More']];nav.innerHTML=defs.map(function(x,k){return '<button data-v="'+x[0]+'" class="'+(k===0?'on':'')+'"><b><span class="nav-ico">'+svg(x[1])+'</span></b><span>'+x[2]+'</span></button>'}).join('');nav.querySelectorAll('button').forEach(function(b){b.onclick=function(){document.querySelectorAll('.view').forEach(function(v){v.classList.remove('active')});var v=document.getElementById(b.dataset.v);if(v)v.classList.add('active');nav.querySelectorAll('button').forEach(function(x){x.classList.toggle('on',x===b)});if(b.dataset.v==='dashboard')setTimeout(render,0);if(b.dataset.v==='tickets'&&typeof tickets==='function')tickets();window.scrollTo(0,0)}})}
function morePanel(){var more=document.getElementById('more');if(!more)return;if(!document.getElementById('freeNotifPanel'))more.insertAdjacentHTML('beforeend','<div class="notif-panel" id="freeNotifPanel"><h3>Travel alerts</h3><p>Free alerts for Prepare, Leave Soon and Leave Now. System notifications are used only when the device/browser supports them; the app still shows the schedule offline without them.</p><button id="enableAlerts">ENABLE FREE ALERTS</button></div>')}
function setup(){var dash=document.getElementById('dashboard');if(!dash)return;Array.prototype.slice.call(dash.children).forEach(function(x){if(x.id!=='travelerProfile')x.classList.add('legacy-dashboard')});var host=document.getElementById('dailyAssistant');if(!host){host=document.createElement('div');host.id='dailyAssistant';dash.appendChild(host)}modernNav();morePanel();render();if(window.Notification&&Notification.permission==='granted')run.alerts=true;var eb=document.getElementById('enableAlerts');if(eb)eb.onclick=function(){if(!('Notification'in window)){alert('System notifications are not supported here. In-app timing remains active.');return}Notification.requestPermission().then(function(p){run.alerts=p==='granted';save();eb.textContent=run.alerts?'ALERTS ENABLED':'ENABLE FREE ALERTS'})}}
function maybeNotify(){if(!run.alerts||!('Notification'in window)||Notification.permission!=='granted')return;var cp=parts(),a=byDate(cp.date);a.forEach(function(i){var sm=min(i.start);if(sm==null)return;var lb=sm-travelBuffer(i),d=lb-cp.mins,key='n-'+cp.date+'-'+i.id+'-';var title=null,body=null;if(d===30){title='Prepare';body=i.name+' · leave '+hm(lb)}else if(d===10){title='Leave soon';body=i.name+' · leave in 10 min'}else if(d===0){title=(i.type==='flight'||i.type==='train')?'LEAVE NOW — fixed transport':'Leave now';body=i.name}if(title&&!run[key+d]){try{new Notification(title,{body:body,tag:key+d})}catch(e){}run[key+d]=1;save()}})}
window.addEventListener('scroll',armReturn,{passive:true});window.addEventListener('touchstart',armReturn,{passive:true});window.addEventListener('tripstatechange',function(){setTimeout(render,20)});setup();setInterval(function(){var cp=parts();var clock=document.querySelector('.today-clock');if(clock)clock.textContent='CHINA TIME · '+cp.clock;maybeNotify()},60000);setTimeout(maybeNotify,1500);
}());