(function(){
  'use strict';
  function chinaDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
  function ico(t){return({flight:'✈️',arrival:'📍',hotel:'🏨',attraction:'🏯',restaurant:'🍽️',transfer:'🚕',tour:'🚌',train:'🚄',activity:'🛶',area:'🚶',shopping:'🛍️'})[t]||'📍';}
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function addStyles(){if(document.getElementById('pretripPreviewStyles'))return;var s=document.createElement('style');s.id='pretripPreviewStyles';s.textContent='.preview-shell{display:grid;gap:12px}.preview-hero{background:linear-gradient(135deg,#7a1f2b,#9d3844);color:#fff;border-radius:24px;padding:20px;box-shadow:var(--shadow)}.preview-hero .tiny{font-size:10px;font-weight:900;letter-spacing:.12em;opacity:.8}.preview-hero h2{font-size:30px;line-height:1;margin:6px 0}.preview-hero p{margin:0;color:#f5dde1;font-size:12px}.preview-card{background:var(--card);border:1px solid var(--line);border-radius:20px;padding:15px}.preview-card h3{margin:0 0 10px;font-size:17px}.preview-row{display:grid;grid-template-columns:78px 34px 1fr;gap:8px;align-items:start;padding:10px 0;border-top:1px solid var(--line)}.preview-row:first-of-type{border-top:0}.preview-time{font-size:11px;font-weight:900;color:#7a1f2b}.preview-icon{font-size:20px}.preview-name{font-size:13px;font-weight:850}.preview-zh{font-size:11px;color:#60796f;margin-top:2px}.preview-note{font-size:10.5px;color:var(--muted);margin-top:3px}.preview-fixed{display:inline-flex;margin-top:5px;font-size:9px;font-weight:800;background:#deece4;color:#143a31;padding:4px 7px;border-radius:999px}.preview-tip{background:#fff8e9;border:1px solid #ead8ae;border-radius:16px;padding:12px;font-size:11.5px;color:#76551f}@media(max-width:390px){.preview-row{grid-template-columns:68px 30px 1fr}.preview-hero h2{font-size:27px}}';document.head.appendChild(s);}
  function render(){var d=chinaDate();if(d>='2026-09-05')return;var host=document.getElementById('dailyAssistant');if(!host)return;var a=(window.ITINERARY||[]).filter(function(i){return i.active!==false&&i.date==='2026-09-05';});if(!a.length)return;addStyles();a.sort(function(x,y){return String(x.start||x.time||'99:99').localeCompare(String(y.start||y.time||'99:99'));});var rows=a.map(function(i){return '<div class="preview-row"><div class="preview-time">'+esc(i.time)+'</div><div class="preview-icon">'+ico(i.type)+'</div><div><div class="preview-name">'+esc(i.name)+'</div><div class="preview-zh">'+esc(i.nameZh||'')+'</div>'+(i.notes?'<div class="preview-note">'+esc(i.notes)+'</div>':'')+(i.locked?'<span class="preview-fixed">FIXED</span>':'')+'</div></div>';}).join('');host.className='daily-assistant theme-beijing';host.innerHTML='<div class="preview-shell"><div class="preview-hero"><div class="tiny">PREVIEW · DAY 1 · SEP 5</div><h2>Beijing 北京</h2><p>Your real Today screen will switch to live NOW / NEXT automatically on Sep 5.</p></div><div class="preview-card"><h3>Day 1 Timeline</h3>'+rows+'</div><div class="preview-tip"><b>Ready for travel:</b> this preview uses the same final itinerary that powers NOW, NEXT, leave-by and booking links during the trip.</div></div>';}
  render();
  document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('[data-v="dashboard"]');if(b)setTimeout(render,0);});
}());