(function(){
'use strict';
var RUN_KEY='china-trip-2026-daily-state',TZ='Asia/Shanghai',idleTimer=null,ignoreScroll=false;
var run={};try{run=JSON.parse(localStorage.getItem(RUN_KEY)||'{}');}catch(e){run={};}
function save(){localStorage.setItem(RUN_KEY,JSON.stringify(run));}
function cp(){var p=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()),o={};p.forEach(function(x){if(x.type!=='literal')o[x.type]=x.value;});return{date:o.year+'-'+o.month+'-'+o.day,mins:+o.hour*60 + +o.minute,clock:o.hour+':'+o.minute};}
function mins(s){if(!s||!/^[0-2]?\d:[0-5]\d$/.test(s))return null;var a=s.split(':').map(Number);return a[0]*60+a[1];}
function hm(m){m=(m+1440)%1440;return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0');}
function icon(t){return({train:'🚄',flight:'✈️',attraction:'🏯',show:'🎭',activity:'🛶',transfer:'🚕',restaurant:'🍽️',hotel:'🏨',shopping:'🛍️',tour:'🚌',area:'🚶',arrival:'📍'})[t]||'📍';}
function items(){return (window.ITINERARY||[]).filter(function(i){return i.active!==false;}).slice().sort(function(a,b){return a.date.localeCompare(b.date)||(+a.day)-(+b.day)||String(a.start||'99:99').localeCompare(String(b.start||'99:99'));});}
function byDate(d){return items().filter(function(i){return i.date===d;});}
function state(i){return run[i.id]||{};}
function buffer(i){if(i.type==='arrival'||i.type==='hotel'||i.start==null)return null;if(i.leaveBuffer!=null)return i.leaveBuffer;if(i.type==='flight')return 150;if(i.type==='train')return 90;if(i.type==='tour')return 35;if(i.type==='attraction'||i.type==='activity')return 30;if(i.type==='transfer')return 10;return 20;}
function leave(i){var m=mins(i.start),b=buffer(i);return m==null||b==null?'—':hm(m-b);}
function pill(i){var s=state(i);if(s.skipped)return '<span class="tpill muted">Skipped</span>';if(s.done)return '<span class="tpill done">Done</span>';if(i.pending)return '<span class="tpill pending">Pending</span>';if(i.optional)return '<span class="tpill optional">Optional</span>';if(i.locked)return '<span class="tpill fixed">Fixed</span>';return '';}
function choose(a,now){var u=a.filter(function(i){return mins(i.start)!=null&&!state(i).skipped;});if(!u.length)return{now:a[0]||null,next:a[1]||null};var k=-1;for(var n=0;n<u.length;n++)if(mins(u[n].start)<=now)k=n;if(k<0)return{now:null,next:u[0]};return{now:u[k],next:u[k+1]||null};}
function stage(p,now){if(p.next){var d=mins(p.next.start)-now;if(d>60)return'READY';if(d>15)return'PREPARE';if(d>=0)return'LEAVE SOON';}return p.now?'NOW':'WRAP UP';}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function row(i,isCurrent){var ticket=i.bookable?'<span>🎟 '+(i.defaultStatus==='booked'||i.locked&&/Booked/i.test(i.price||'')?'Booked':'Ticket')+'</span>':'';return '<article class="trip-row '+(isCurrent?'current-row':'')+'" id="event-'+esc(i.id)+'"><div class="trip-time">'+esc(i.time)+'</div><div class="trip-ico">'+icon(i.type)+'</div><div class="trip-copy"><div class="trip-title">'+esc(i.name)+' '+pill(i)+'</div><div class="trip-zh">'+esc(i.nameZh||'')+'</div>'+(i.notes?'<div class="trip-note">'+esc(i.notes)+'</div>':'')+'<div class="action-bundle"><span>🕐 '+esc(i.time)+'</span>'+(leave(i)!=='—'?'<span>🚕 Leave '+leave(i)+'</span>':'')+ticket+'<button data-driver="'+esc(i.id)+'">🇨🇳 中文</button>'+(i.notes?'<span>📝 Note</span>':'')+'</div></div></article>';}
function dayBlock(day,date,a,currentId){var city=a[0]?a[0].city:'',zh=a[0]?a[0].cityZh:'';return '<section class="full-day" id="day-'+day+'" data-date="'+date+'"><div class="day-sticky"><div><small>DAY '+day+' · '+date.slice(5)+'</small><h3>'+esc(city)+' <span>'+esc(zh)+'</span></h3></div><button class="jump-now" data-jumpnow>NOW</button></div>'+a.map(function(i){return row(i,i.id===currentId);}).join('')+'</section>';}
function focusCard(i,label){if(!i)return'';return '<article class="focus-card"><div class="focus-kicker">'+label+' '+pill(i)+'</div><div class="focus-main"><div class="focus-icon">'+icon(i.type)+'</div><div><h2>'+esc(i.name)+'</h2><div class="focus-zh">'+esc(i.nameZh||'')+'</div></div></div><div class="focus-grid"><div><small>TIME</small><b>'+esc(i.time)+'</b></div><div><small>LEAVE BY</small><b>'+leave(i)+'</b></div><div><small>STATUS</small><b>'+(i.optional?'Optional':i.pending?'Pending':i.locked?'Fixed':'Planned')+'</b></div></div>'+(i.notes?'<p class="focus-note">'+esc(i.notes)+'</p>':'')+'<div class="quick-strip"><button data-driver="'+esc(i.id)+'">🇨🇳 SHOW TO DRIVER</button><button data-copy="'+esc(i.id)+'">Copy 中文</button></div><div class="today-actions"><button data-act="done" data-id="'+esc(i.id)+'">✓ Done</button><button data-act="skip" data-id="'+esc(i.id)+'">Skip</button><button data-act="late" data-id="'+esc(i.id)+'">Running Late</button></div></article>';}
function tomorrowBrief(date){var d=new Date(date+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+1);var ds=d.toISOString().slice(0,10),a=byDate(ds);if(!a.length)return'';var first=a.find(function(i){return mins(i.start)!=null;});return '<button class="tomorrow-card" data-dayjump="'+a[0].day+'"><div class="tiny-label">TOMORROW · TAP TO VIEW</div><h3>Day '+a[0].day+' · '+esc(a[0].city)+' <span>'+esc(a[0].cityZh)+'</span></h3><div class="tomorrow-grid"><div><small>FIRST PLAN</small><b>'+(first?esc(first.time):'Flexible')+'</b></div><div><small>LEAVE BY</small><b>'+(first?leave(first):'—')+'</b></div><div><small>FIXED</small><b>'+a.filter(function(i){return i.locked;}).length+'</b></div></div></button>';}
function css(){if(document.getElementById('todayV2css'))return;var s=document.createElement('style');s.id='todayV2css';s.textContent='.trip-scroll-intro{font-size:12px;color:#6f776f;margin:10px 3px 16px}.all-days{display:block}.full-day{background:#fffdfa;border:1px solid #e5ddd1;border-radius:24px;margin:18px 0;overflow:hidden;scroll-margin-top:100px}.day-sticky{position:sticky;top:0;z-index:3;background:rgba(255,253,250,.96);backdrop-filter:blur(12px);display:flex;justify-content:space-between;align-items:center;padding:15px 16px;border-bottom:1px solid #eee5da}.day-sticky small{font-weight:900;letter-spacing:.08em;color:#8b2537}.day-sticky h3{margin:2px 0 0;color:#143a31;font-size:21px}.day-sticky h3 span{font-weight:600;color:#698078}.jump-now{font-size:10px;padding:7px 10px}.trip-row{display:grid;grid-template-columns:86px 38px 1fr;gap:8px;padding:15px 14px;border-bottom:1px solid #eee5da}.trip-row:last-child{border-bottom:0}.trip-row.current-row{background:#f2f7f2;box-shadow:inset 4px 0 #143a31}.trip-time{font-weight:900;color:#8b2537}.trip-ico{font-size:20px}.trip-title{font-weight:900;color:#17382f;font-size:15px}.trip-zh{color:#608078;font-size:13px;margin-top:2px}.trip-note{color:#777;font-size:12px;line-height:1.35;margin-top:5px}.action-bundle{display:flex;flex-wrap:wrap;gap:5px;margin-top:8px}.action-bundle span,.action-bundle button{font-size:9px;border:1px solid #e1ded7;background:#f8f7f2;color:#45534d;border-radius:999px;padding:5px 7px}.today-scroll-hint{display:flex;justify-content:space-between;align-items:center;margin:12px 2px}.today-scroll-hint button{font-size:11px}.tomorrow-card{width:100%;text-align:left;border:0}.live-anchor{scroll-margin-top:96px}@media(max-width:430px){.trip-row{grid-template-columns:80px 34px 1fr;padding:13px 10px}.trip-time{font-size:12px}.day-sticky{padding:13px 12px}.action-bundle{gap:4px}}';document.head.appendChild(s);}
function render(){var host=document.getElementById('dailyAssistant');if(!host)return;css();var c=cp(),all=items(),tripStart='2026-09-05',tripEnd='2026-09-21',liveDate=c.date<tripStart?tripStart:(c.date>tripEnd?tripEnd:c.date),today=byDate(liveDate),p=choose(today,c.date===liveDate?c.mins:-1),focus=p.now||p.next||today[0],currentId=focus&&focus.id,pre=c.date<tripStart,post=c.date>tripEnd,city=today[0]?today[0].city:'China';host.className='daily-assistant theme-beijing';var top;if(pre){top='<div class="assistant-hero"><div><div class="tiny-label">PREVIEW · DAY 1 · SEP 5</div><h1>'+esc(city)+' <span>'+(today[0]?esc(today[0].cityZh):'')+'</span></h1><div class="stage-chip">READY</div></div><button id="travelMode" class="travel-toggle">Preview</button></div><p class="trip-scroll-intro">Scroll through the entire trip now. During the trip this screen automatically returns to the current date and current activity after you stop browsing.</p>'+focusCard(focus,'FIRST UP')+tomorrowBrief(liveDate);}else if(post){top='<div class="pretrip"><div class="tiny-label">TRIP COMPLETE</div><h2>China Trip</h2></div>';}else{top='<div class="assistant-hero live-anchor" id="liveAnchor"><div><div class="tiny-label">DAY '+today[0].day+' · '+c.date+' · CHINA TIME '+c.clock+'</div><h1>'+esc(city)+' <span>'+esc(today[0].cityZh)+'</span></h1><div class="stage-chip">'+stage(p,c.mins)+'</div></div><button id="travelMode" class="travel-toggle">'+(run.travelMode?'Exit Travel Mode':'Travel Mode')+'</button></div>'+(run.lateAt&&Date.now()-run.lateAt<21600000?'<div class="late-banner">⚠ Running late: fixed transport first; optional items can be skipped.</div>':'')+focusCard(focus,p.now?'NOW':'NEXT')+tomorrowBrief(liveDate);}var dates=[];all.forEach(function(i){if(dates.indexOf(i.date)<0)dates.push(i.date);});var blocks=dates.map(function(d){var a=byDate(d);return dayBlock(a[0].day,d,a,currentId);}).join('');host.innerHTML=top+'<div class="today-scroll-hint"><strong>Full Trip · Sep 5–21</strong><button data-jumpnow>Back to current</button></div><div class="all-days">'+blocks+'</div>';wire();}
function currentAnchor(){var c=cp(),d=c.date<'2026-09-05'?'2026-09-05':(c.date>'2026-09-21'?'2026-09-21':c.date),a=byDate(d),p=choose(a,c.date===d?c.mins:-1),i=p.now||p.next||a[0];return i?document.getElementById('event-'+i.id):document.getElementById('day-1');}
function returnNow(smooth){var el=currentAnchor();if(!el)return;ignoreScroll=true;el.scrollIntoView({behavior:smooth?'smooth':'auto',block:'center'});setTimeout(function(){ignoreScroll=false;},900);}
function scheduleReturn(){if(ignoreScroll)return;clearTimeout(idleTimer);idleTimer=setTimeout(function(){returnNow(true);},10000);}
function wire(){var tm=document.getElementById('travelMode');if(tm)tm.onclick=function(){run.travelMode=!run.travelMode;save();render();returnNow(false);};document.querySelectorAll('[data-act]').forEach(function(b){b.onclick=function(){var id=b.dataset.id,act=b.dataset.act;run[id]=run[id]||{};if(act==='done'){run[id].done=!run[id].done;run[id].skipped=false;}if(act==='skip'){run[id].skipped=!run[id].skipped;run[id].done=false;}if(act==='late')run.lateAt=Date.now();save();render();};});document.querySelectorAll('[data-driver]').forEach(function(b){b.onclick=function(){var i=items().find(function(x){return x.id===b.dataset.driver;});if(!i)return;var old=document.getElementById('driverSheet');if(old)old.remove();var d=document.createElement('div');d.id='driverSheet';d.className='driver-sheet';d.innerHTML='<button class="driver-close">×</button><div class="driver-label">请带我去 / PLEASE TAKE ME TO</div><div class="driver-zh">'+esc(i.nameZh||i.name)+'</div><div class="driver-en">'+esc(i.name)+'</div>'+(i.notes?'<div class="driver-note">'+esc(i.notes)+'</div>':'');document.body.appendChild(d);d.querySelector('.driver-close').onclick=function(){d.remove();};};});document.querySelectorAll('[data-copy]').forEach(function(b){b.onclick=function(){var i=items().find(function(x){return x.id===b.dataset.copy;});if(i&&navigator.clipboard)navigator.clipboard.writeText(i.nameZh||i.name);};});document.querySelectorAll('[data-jumpnow]').forEach(function(b){b.onclick=function(){returnNow(true);};});document.querySelectorAll('[data-dayjump]').forEach(function(b){b.onclick=function(){var x=document.getElementById('day-'+b.dataset.dayjump);if(x)x.scrollIntoView({behavior:'smooth',block:'start'});};});}
function setupHome(){var dash=document.getElementById('dashboard');if(!dash)return;Array.prototype.slice.call(dash.children).forEach(function(x){x.classList.add('legacy-dashboard');});var host=document.createElement('div');host.id='dailyAssistant';host.className='daily-assistant';dash.insertBefore(host,dash.firstChild);render();setTimeout(function(){returnNow(false);},250);window.addEventListener('scroll',scheduleReturn,{passive:true});window.addEventListener('touchend',scheduleReturn,{passive:true});}
function setupNav(){var nav=document.querySelector('.bottom-nav');if(!nav)return;if(!document.getElementById('more')){var more=document.createElement('section');more.id='more';more.className='view';more.innerHTML='<div class="page-head"><div><div class="eyebrow">MORE</div><h2>Trip Tools</h2><p>Reservations and booking deadlines.</p></div></div><div class="more-grid"><button data-open-view="bookings"><b>✓</b><span>Bookings</span><small>Manage reservations & status</small></button><button data-open-view="calendar"><b>◫</b><span>Booking Calendar</span><small>Opening dates & deadlines</small></button></div>';document.querySelector('main').appendChild(more);}nav.innerHTML='<button data-v="dashboard" class="on"><b>◉</b><span>Today</span></button><button data-v="timeline"><b>🗓</b><span>Trip</span></button><button data-v="tickets"><b>🎟</b><span>Tickets</span></button><button data-v="checklist"><b>✓</b><span>Checklist</span></button><button data-v="more"><b>•••</b><span>More</span></button>';function go(id,navId){document.querySelectorAll('.view').forEach(function(v){v.classList.remove('active');});var x=document.getElementById(id);if(x)x.classList.add('active');nav.querySelectorAll('button').forEach(function(b){b.classList.toggle('on',b.dataset.v===(navId||id));});if(id==='tickets'&&window.tickets)tickets();window.scrollTo(0,0);if(id==='dashboard')setTimeout(function(){returnNow(false);},80);}nav.querySelectorAll('button').forEach(function(b){b.onclick=function(){go(b.dataset.v);};});document.querySelectorAll('[data-open-view]').forEach(function(b){b.onclick=function(){go(b.dataset.openView,'more');};});}
function setupHeader(){var h=document.querySelector('.topbar h1');if(h)h.textContent='China Trip Assistant';var p=document.querySelector('.topbar p');if(p)p.textContent='Sep 5–21 · Offline-ready';}
setupHeader();setupHome();setupNav();window.addEventListener('tripstatechange',function(){render();});if(cp().date>='2026-09-05'&&cp().date<='2026-09-21')setInterval(function(){render();},60000);
}());